### ISSUE TITLE
Summarise issue or request about Issue Pigeon Settings

### ISSUE THREAD

**Issue by mike2real** [anaran/IssuePigeonFirefox#18]
See:

resource://issue-pigeon-at-addons-dot-mozilla-dot-org/data/anaran-jetpack-content/settings.html

Details:

http://mzl.la/1vxCDgA

**Comment by mike2real** [comment]
Please help fix problem

**Comment by anaran** [comment]
Please describe:

# What did you do?

1. steps to reproduce

# What happened?

actual results

# What should have happened?

expected results
